language: go

matrix:
  fast_finish: true
  include:
  - go: 1.10.x
  - go: 1.11.x
  - go: 1.12.x

install:
  - make install

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
